// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ETH Explorer",
    platforms: [
        .iOS("16.0"),
        .macCatalyst("16.0")
    ],
    products: [
        .iOSApplication(
            name: "ETH Explorer",
            targets: ["AppModule"],
            bundleIdentifier: "com.nossa.wwdc23.eth",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .lightningBolt),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/Sajjon/EllipticCurveKit.git", "1.0.0"..<"2.0.0"),
        .package(url: "https://github.com/krzyzanowskim/CryptoSwift.git", "1.0.0"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "EllipticCurveKit", package: "ellipticcurvekit"),
                .product(name: "CryptoSwift", package: "cryptoswift")
            ],
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)